name: jaffle_shop

profile: jaffle_shop

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  jaffle_shop:
    # Configurações globais para todos os seeds
    +schema: dw_seeds
    
    # Seeds com delimitador ponto e vírgula
    customers:
      +delimiter: ";"

models:
  jaffle_shop:
    staging:
      +schema: staging
      +materialized: table
      +tags: ['staging']

      intermediate:
        +materialized: ephemeral
        +tags: ['intermediate']
    marts:
      +schema: marts
      +materialized: table
      +tags: ['marts']

    # Materialize staging models as views, and marts as tables


