name: exemplo_dbt

profile: exemplo_dbt

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  exemplo_dbt:
    # Configurações globais para todos os seeds
    +schema: dw_seeds

    # Seeds com delimitador ponto e vírgula
    customers:
      +delimiter: ";"

models:
  exemplo_dbt:
    staging:
      +schema: staging
      +materialized: table
      +tags: ['staging']

      intermediate:
        +materialized: ephemeral
        +tags: ['intermediate']
    marts:
      +schema: marts
      +materialized: table
      +tags: ['marts']

    # Materialize staging models as views e marts como tabelas
